Added check_if_successful function and other minor changes
Added a check_if_successful function that will be used to check if a command was successful.  Other minor changes.

diff --git a/brrb b/brrb
--- a/brrb
+++ b/brrb
@@ -16,11 +16,26 @@
 # Cambridge, MA 02139, USA.
 
 # Create a function called to check if a needed command is available
-function is_available()
+function check_if_available()
 {
   if ! command -v "$1" > /dev/null
   then
-    echo "Command $1 is required but is not available."
+    echo "Command $1 is required but is not available." >&2
+    exit 1
+  fi
+}
+
+# Create a function called to check if a command was successful
+function check_if_successful()
+{
+  # Save the passed in variable
+  local command="$1"
+  local -i exit_code="$2"
+
+  # Check if the command was not successful
+  if (( $exit_code != 0 ))
+  then
+    echo "Command $command failed." >&2
     exit 1
   fi
 }
@@ -43,10 +58,10 @@ function perform_backup()
     -d "bs=256M iflag=fullblock status=progress" -c -x "-$compression_level -T 0" -a
 
   # Check if performing the backup failed
-  if [[ $? -eq 1 ]]
+  if (( $? != 0 ))
   then
     # Return an empty string
-    echo -n ""
+    # echo -n ""
     return 1
   fi
 
@@ -83,10 +98,10 @@ function perform_backup_with_dependees()
       -l "-B 524288 -0 -S none -N" -c -x "-$compression_level -T 0" -a
 
     # Check if performing the backup failed
-    if [[ $? -eq 1 ]]
+    if (( $? != 0 ))
     then
       # Return an empty string
-      echo -n ""
+      # echo -n ""
       return 1
     fi
 
@@ -109,10 +124,10 @@ function perform_backup_with_dependees()
       -l "-B 524288 -0 -S none -N" -c -x "-$compression_level -T 0" -a
 
     # Check if performing the backup failed
-    if [[ $? -eq 1 ]]
+    if (( $? != 0 ))
     then
       # Return an empty string
-      echo -n ""
+      # echo -n ""
       return 1
     fi
 
@@ -127,7 +142,7 @@ function perform_backup_with_dependees()
   fi
 
   # Return the path to the backup file
-  echo "$location/$device_name.dd.xdelta3.xz"
+  echo -n "$location/$device_name.dd.xdelta3.xz"
   return 0
 }
 
@@ -145,13 +160,13 @@ function verify_backup()
 
   # Perform a restore and pipe it to the hash command
   local hash="$(./ddinc -r "$location/$device_name.dd.xz" \
-    -d "bs=256M iflag=fullblock status=progress" -c | sha1sum -z)"
+    -d "bs=256M iflag=fullblock status=progress" -c | sha1sum)"
 
   # Check if verifying the backup failed
-  if [[ $? -eq 1 ]]
+  if (( $? != 0 ))
   then
     # Return an empty string
-    echo -n ""
+    # echo -n ""
     return 1
   fi
 
@@ -175,13 +190,13 @@ function verify_backup_with_dependees()
   # Perform a restore and pipe it to the hash command
   local hash="$(./ddinc -f "$location/$device_name.dd.dependees" \
     -r "$location/$device_name.dd.xdelta3.xz" -d "bs=256M iflag=fullblock status=progress" -c | \
-    sha1sum -z)"
+    sha1sum)"
   
   # Check if verifying the backup failed
-  if [[ $? -eq 1 ]]
+  if (( $? != 0 ))
   then
     # Return an empty string
-    echo -n ""
+    # echo -n ""
     return 1
   fi
 
@@ -222,20 +237,20 @@ do
       ;;
     h)
       echo "Usage: brrb (-b device | -r device) -l location [-d dependee_location]" \
-           "[-0..9] [-f]"
-      echo
-      echo "-b    device to backup (can be specified multiple times)"
-      echo "-r    device to restore (can be specified multiple times)"
-      echo "-l    backup location"
-      echo "-d    backup dependee location"
-      echo "-0..9 compression level (default is 0)"
-      echo "-f    fast mode that skips re-computing hashes"
-      echo
-      echo "Backup example"
-      echo "brrb -b /dev/sda -b /dev/sdb -l ./backup/february -d ./backup/january"
-      echo
-      echo "Restore example"
-      echo "brrb -r /dev/sda -r /dev/sdb -l ./backup/february"
+           "[-0..9] [-f]" >&2
+      echo >&2
+      echo "-b    device to backup (can be specified multiple times)" >&2
+      echo "-r    device to restore (can be specified multiple times)" >&2
+      echo "-l    backup location" >&2
+      echo "-d    backup dependee location" >&2
+      echo "-0..9 compression level (default is 0)" >&2
+      echo "-f    fast mode that skips re-computing hashes" >&2
+      echo >&2
+      echo "Backup example" >&2
+      echo "brrb -b /dev/sda -b /dev/sdb -l ./backup/february -d ./backup/january" >&2
+      echo >&2
+      echo "Restore example" >&2
+      echo "brrb -r /dev/sda -r /dev/sdb -l ./backup/february" >&2
 
       exit 0
       ;;
@@ -244,28 +259,28 @@ done
 shift $((OPTIND - 1))
 
 # Check if the needed commands are available
-is_available "mv"
-is_available "realpath"
-is_available "rm"
-is_available "par2"
-is_available "sha1sum"
+check_if_available "mv"
+check_if_available "realpath"
+check_if_available "rm"
+check_if_available "par2"
+check_if_available "sha1sum"
 
 # Make sure a backup device or a restore device was specified and not both
-if [[ ${#backup_devices[@]} -eq 0 && ${#restore_devices[@]} -eq 0 ]]
+if (( ${#backup_devices[@]} == 0 && ${#restore_devices[@]} == 0 ))
 then
-  echo "No backup devices or restore devices were specified.  See help (-h) for details."
+  echo "No backup devices or restore devices were specified.  See help (-h) for details." >&2
   exit 1
 fi
-if [[ ${#backup_devices[@]} -ne 0 && ${#restore_devices[@]} -ne 0 ]]
+if (( ${#backup_devices[@]} != 0 && ${#restore_devices[@]} != 0 ))
 then
-  echo "Both backup and restore devices were specified.  See help (-h) for details."
+  echo "Both backup and restore devices were specified.  See help (-h) for details." >&2
   exit 1
 fi
 
 # Make sure a location was specified
 if [[ -z "$location" ]]
 then
-  echo "No backup location was specified.  See help (-h) for details."
+  echo "No backup location was specified.  See help (-h) for details." >&2
   exit 1
 fi
 
@@ -292,7 +307,7 @@ then
       -e "$location/$device_name.dd.xdelta3.xz.par2" || \
       -e "$location/$device_name.dd.xdelta3.xz.vol00+50.par2")) ]]
     then
-      echo "One or more backup files already exist in the specified backup location."
+      echo "One or more backup files already exist in the specified backup location." >&2
       exit 1
     fi
   done
@@ -311,7 +326,7 @@ then
     # Asynchronously run the following commands
     {
       # Compute the device hash by running the hash command
-      hash="$(sha1sum -z "$device")"
+      hash="$(sha1sum "$device")"
 
       # Write just the hash to a file
       echo -n "${hash%% *}" > "$location/${device##*/}.dd.sha1"
@@ -356,9 +371,9 @@ then
     fi
 
     # Check if the backup failed
-    if [[ $? -eq 1 ]]
+    if (( $? != 0 ))
     then
-      echo "An error has occurred performing the backup."
+      echo "An error has occurred performing the backup." >&2
       exit 1
     fi
 
@@ -369,7 +384,7 @@ then
     echo "Computing \"${device_backup_file_map["$device"]}\" backup file hash ..."
 
     # Compute the backup file hash by running the hash command
-    hash="$(sha1sum -z "${device_backup_file_map["$device"]}")"
+    hash="$(sha1sum "${device_backup_file_map["$device"]}")"
 
     # Write just the hash to a file
     echo -n "${hash%% *}" > "${device_backup_file_map["$device"]}.sha1"
@@ -395,9 +410,12 @@ then
 
     # Delete unnecessary par2 index file
     rm "${device_backup_file_map["$device"]}.par2"
+    check_if_successful "rm" $?
 
     # Rename actual par2 file
-    mv "${device_backup_file_map["$device"]}.vol00+50.par2" "${device_backup_file_map["$device"]}.par2"
+    mv "${device_backup_file_map["$device"]}.vol00+50.par2" \
+      "${device_backup_file_map["$device"]}.par2"
+    check_if_successful "mv" $?
   done
 
   # Make things pretty
@@ -440,13 +458,14 @@ then
     then
       echo "which matches the \"$device\" device hash."
     else
-      echo "which does NOT match the \"$device\" device hash.  An error has occurred."
+      echo "which does NOT match the \"$device\" device hash."
+      echo "An error has occurred." >&2
       exit 1
     fi
   done
 
   # Check if fast mode is disabled
-  if [[ $fast_mode -eq 0 ]]
+  if (( $fast_mode == 0 ))
   then
     # Make things pretty
     echo
@@ -458,7 +477,7 @@ then
       echo "Re-computing \"${device_backup_file_map["$device"]}\" backup file hash ..."
 
       # Compute the backup file hash by running the hash command and keep just the hash
-      hash="$(sha1sum -z "${device_backup_file_map["$device"]}")"
+      hash="$(sha1sum "${device_backup_file_map["$device"]}")"
       hash="${hash%% *}"
 
       # Print the hash
@@ -470,7 +489,8 @@ then
       then
         echo "which matches the original hash."
       else
-        echo "which does NOT match the original hash.  An error has occurred."
+        echo "which does NOT match the original hash."
+        echo "An error has occurred." >&2
       fi
     done
 
@@ -486,7 +506,7 @@ then
       for device in "${backup_devices[@]}"
       do
         # Run the hash comand
-        sha1sum -z $device &
+        sha1sum $device &
       done
     )
 
@@ -509,7 +529,8 @@ then
       then
         echo "which matches the original hash."
       else
-        echo "which does NOT match the original hash.  An error has occurred."
+        echo "which does NOT match the original hash."
+        echo "An error has occurred." >&2
       fi
     done
   fi
